# fly.toml file generated for api-volvo-cars-laravel on 2022-10-08T09:15:33-03:00

app = "api-volvo-cars-laravel"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.0"

[env]
  APP_ENV = "development"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  DB_CONNECTION="mysql"
  DB_HOST="us-east.connect.psdb.cloud"
  DB_PORT=3306
  DB_DATABASE="api-volvo-cars-laravel"
  DB_USERNAME="gwuvco5l1lmq93xvfiio"
  DB_PASSWORD="pscale_pw_uFhcUce3EwLxdnkx6V4istKdOVKhjZhPyWlOTzP8hAV"
  MYSQL_ATTR_SSL_CA="/etc/ssl/certs/ca-certificates.crt"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
